In [3]:
import pandas as pd
import duckdb

In [112]:
conn = duckdb.connect("taxinyc.db")

In [7]:
conn.execute("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'main'
""").df()

      table_name
0          trips
1  trips_flagged
2       clean_db
3   clean_yellow

In [8]:
conn.execute(
    """ 
    CREATE TABLE IF NOT EXISTS combined_trips AS
    SELECT * 
    FROM read_parquet('../data/raw/yellow/*.parquet')
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

      Count
0  48722602

In [11]:
conn.execute(
    """ 
    SELECT * FROM combined_trips LIMIT 5
    """
).df()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [14]:
conn.execute(
    """ 
    SUMMARIZE combined_trips;
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,7,4,1.8601995845788368,0.6782855211602725,2,2,2,48722602,0.00
1,tpep_pickup_datetime,TIMESTAMP,2007-12-05 18:45:00,2025-12-31 23:59:59,19363052,2025-07-06 05:22:36.621952,None,2025-04-08 14:06:48.041509,2025-07-03 17:27:40.797311,2025-10-06 09:00:49.281803,48722602,0.00
2,tpep_dropoff_datetime,TIMESTAMP,2007-12-05 19:02:00,2026-01-05 13:00:34,20705652,2025-07-06 05:39:57.973512,None,2025-04-08 10:50:31.31837,2025-07-03 22:59:47.470839,2025-10-06 08:32:02.500046,48722602,0.00
3,passenger_count,BIGINT,0,9,11,1.2954911827605122,0.7291638933484583,1,1,1,48722602,23.83
4,trip_distance,DOUBLE,0.0,397994.37,8495,6.842892016522826,649.3613312608348,1.0382721236737265,1.8467423679199952,3.6973671588322063,48722602,0.00
5,RatecodeID,BIGINT,1,99,7,3.225041004337616,14.265148724130462,1,1,1,48722602,23.83
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,48722602,23.83
7,PULocationID,INTEGER,1,265,290,161.5041679834751,66.19732966352633,118,161,232,48722602,0.00
8,DOLocationID,INTEGER,1,265,298,161.10941121330097,70.45459645479511,109,162,233,48722602,0.00
9,payment_type,BIGINT,0,5,6,0.9372241244422865,0.7465483770308788,1,1,1,48722602,0.00
10,fare_amount,DOUBLE,-1807.6,863372.12,18696,18.419375616474984,142.8460677552982,8.656613667040775,13.715852044052673,22.742364435291726,48722602,0.00
11,extra,DOUBLE,-17.39,133.6,211,1.1643626668378675,1.8220569482302782,0.0,0.0,2.5,48722602,0.00
12,mta_tax,DOUBLE,-21.74,5243.38,85,0.4776843369325801,0.7636665000534604,0.5,0.5,0.5,48722602,0.00
13,tip_amount,DOUBLE,-333.33,960.94,6460,2.842250792352514,3.9667582521967932,0.0,2.05803606335873,3.9584506411071976,48722602,0.00
14,tolls_amount,DOUBLE,-148.17,916.87,3876,0.49883479847602175,2.1209719111223806,0.0,0.0,0.0,48722602,0.00
15,improvement_surcharge,DOUBLE,-1.0,2.5,6,0.9503062305662109,0.28309700925355735,1.0,1.0,1.0,48722602,0.00
16,total_amount,DOUBLE,-1832.85,863380.37,46996,26.908800326599778,143.48226145568472,15.719103864767389,21.299840339747966,30.77641276322458,48722602,0.00
17,congestion_surcharge,DOUBLE,-2.5,2.5,6,2.18315487271221,0.9517964982631492,2.5,2.5,2.5,48722602,23.83
18,Airport_fee,DOUBLE,-1.75,6.75,9,0.14519044611059428,0.52532368978357,0.0,0.0,0.0,48722602,23.83
19,cbd_congestion_fee,DOUBLE,-0.75,1.75,7,0.5294610907685102,0.3585220801850694,0.0,0.75,0.75,48722602,0.00

In [51]:
conn.execute(
    """ 
    SELECT COUNT (*) FROM (
            SELECT DISTINCT (*)
            FROM combined_trips
        )
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   count_star()
0      48722601

In [46]:
conn.execute(
    """ 
    SELECT *,
        COUNT (*) AS duplicate_count,
    FROM combined_trips
    GROUP BY ALL
    HAVING COUNT(*) > 1
    ORDER BY duplicate_count DESC
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duplicate_count
0,2,2025-07-05 17:19:29,2025-07-05 17:19:34,1,0.0,1,N,132,132,2,...,0.0,0.5,0.0,0.0,1.0,6.25,0.0,1.75,0.0,2

In [43]:
conn.execute(
    """ 
    SELECT 
        COUNT (*) AS total_trips,
        COUNT (CASE WHEN tpep_pickup_datetime > tpep_dropoff_datetime THEN 1 END) AS impossible_duration,
        COUNT (CASE WHEN tpep_pickup_datetime = tpep_dropoff_datetime THEN 1 END) AS zero_duration,
        COUNT (CASE WHEN tpep_pickup_datetime < tpep_dropoff_datetime THEN 1 END) AS positive_duration,
        impossible_duration + zero_duration + positive_duration AS total_count
    FROM combined_trips
    """
).df()

,total_trips,impossible_duration,zero_duration,positive_duration,total_count
0,48722602,2235,544069,48176298,48722602

In [42]:
conn.execute(
    """ 
    SUMMARIZE (
        SELECT (*)
        FROM combined_trips
        WHERE passenger_count = 0 AND fare_amount = 0 AND total_amount > 0
    )
    """
).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,2,2,1.032258064516129,0.1774014725270341,1,1,1,124,0.0
1,tpep_pickup_datetime,TIMESTAMP,2025-01-01 05:22:35,2025-12-24 14:35:45,127,2025-06-06 19:13:04.008065,None,2025-02-26 14:14:48.5,2025-05-23 07:16:33.5,2025-08-27 14:18:24.5,124,0.0
2,tpep_dropoff_datetime,TIMESTAMP,2025-01-01 05:23:05,2025-12-24 14:37:28,136,2025-06-06 19:19:50.177419,None,2025-02-26 14:15:08,2025-05-23 07:17:50.5,2025-08-27 14:19:02,124,0.0
3,passenger_count,BIGINT,0,0,1,0.0,0.0,0,0,0,124,0.0
4,trip_distance,DOUBLE,0.0,49.8,41,3.8045161290322578,8.07034472569838,0.0,0.13,3.45,124,0.0
5,RatecodeID,BIGINT,1,99,5,7.048387096774194,14.56404685491046,5,5,5,124,0.0
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,124,0.0
7,PULocationID,INTEGER,1,265,51,149.70967741935485,69.00663031577018,127,142,193,124,0.0
8,DOLocationID,INTEGER,1,265,43,172.80645161290323,77.15423023134335,132,163,254,124,0.0
9,payment_type,BIGINT,1,4,4,2.8225806451612905,0.9546496151742933,2,3,4,124,0.0
10,fare_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,124,0.0
11,extra,DOUBLE,0.0,6.75,10,1.1411290322580645,1.9688225236310102,0.0,0.75,0.75,124,0.0
12,mta_tax,DOUBLE,0.0,0.5,2,0.04435483870967742,0.14273884240411958,0.0,0.0,0.0,124,0.0
13,tip_amount,DOUBLE,0.0,150.0,10,4.439112903225807,20.786862213188307,0.0,0.0,0.0,124,0.0
14,tolls_amount,DOUBLE,0.0,300.0,6,3.728225806451613,27.216011548930602,0.0,0.0,0.0,124,0.0
15,improvement_surcharge,DOUBLE,0.0,1.0,2,0.9193548387096774,0.2733940303482413,1.0,1.0,1.0,124,0.0
16,total_amount,DOUBLE,0.75,300.0,33,10.370967741935484,34.73603975113523,1.0,1.75,5.225,124,0.0
17,congestion_surcharge,DOUBLE,0.0,2.5,2,0.14112903225806453,0.5793200523481942,0.0,0.0,0.0,124,0.0
18,Airport_fee,DOUBLE,0.0,1.75,2,0.2963709677419355,0.6590265482857252,0.0,0.0,0.0,124,0.0
19,cbd_congestion_fee,DOUBLE,0.0,0.75,2,0.3024193548387097,0.369401561676025,0.0,0.0,0.75,124,0.0

In [41]:
conn.execute(
    """ 
    SUMMARIZE (
        SELECT (*)
        FROM combined_trips
        WHERE passenger_count = 0 AND fare_amount = 0 AND total_amount = 0
    )
    """
).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,1,1,1.0,0.0,1,1,1,197,0.0
1,tpep_pickup_datetime,TIMESTAMP,2025-01-04 08:37:48,2025-12-30 11:22:27,185,2025-07-14 20:48:06.771574,None,2025-04-07 00:05:46.9375,2025-07-24 23:58:19,2025-10-14 04:02:40,197,0.0
2,tpep_dropoff_datetime,TIMESTAMP,2025-01-04 08:38:18,2025-12-30 11:22:27,221,2025-07-14 20:44:52.182741,None,2025-04-07 00:05:54.6875,2025-07-25 00:11:25.333333,2025-10-14 02:30:34.4375,197,0.0
3,passenger_count,BIGINT,0,0,1,0.0,0.0,0,0,0,197,0.0
4,trip_distance,DOUBLE,0.0,18.3,27,0.8426395939086294,2.726683927757985,0.0,0.0,0.018750000000000003,197,0.0
5,RatecodeID,BIGINT,1,99,5,27.781725888324875,42.785989398900746,1,2,99,197,0.0
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,197,0.0
7,PULocationID,INTEGER,4,264,64,154.26903553299493,67.05688801448741,111,145,229,197,0.0
8,DOLocationID,INTEGER,36,264,43,196.71573604060913,72.7934624089347,138,235,264,197,0.0
9,payment_type,BIGINT,1,5,5,3.0964467005076144,0.8897589466333328,3,3,4,197,0.0
10,fare_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
11,extra,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
12,mta_tax,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
13,tip_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
14,tolls_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
15,improvement_surcharge,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
16,total_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
17,congestion_surcharge,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
18,Airport_fee,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,197,0.0
19,cbd_congestion_fee,DOUBLE,0.0,0.75,2,0.0799492385786802,0.23204173063712127,0.0,0.0,0.0,197,0.0

In [ ]:
conn.execute(
    """ 
    SELECT 
        COUNT (*) AS total_count,
        COUNT (CASE WHEN passenger_count > 0 AND fare_amount > 0 AND total_amount > 0 THEN 1 END) AS positive_passenger_positive_fare_count,
        COUNT (CASE WHEN passenger_count = 0 AND fare_amount = 0 AND total_amount = 0 THEN 1 END) AS zero_passenger_zero_fare_count,
        COUNT (CASE WHEN passenger_count = 0 AND fare_amount = 0 AND total_amount > 0 THEN 1 END) AS zero_passenger_positive_fare_count,
    FROM combined_trips
    """
).df()

,total_count,positive_passenger_positive_fare_count,zero_passenger_zero_fare_count,zero_passenger_positive_fare_count
0,48722602,36031345,197,124

In [35]:
conn.execute(
    """ 
    SELECT
        COUNT (*) AS total_trips,
        COUNT (CASE WHEN total_amount > 0 AND fare_amount > 0 THEN 1 END) AS valid_trips,
        COUNT (CASE WHEN total_amount = 0 AND fare_amount = 0 THEN 1 END) AS zero_amount_trips,
        COUNT (CASE WHEN total_amount > 0 AND fare_amount = 0 THEN 1 END) AS zero_fare_trips,
        COUNT (CASE WHEN total_amount < 0 AND fare_amount < 0 THEN 1 END) AS negative_amount_trips,
        COUNT (CASE WHEN total_amount = 0 AND fare_amount > 0 THEN 1 END) AS data_corrupt,
        COUNT (CASE WHEN total_amount < 0 AND fare_amount > 0 THEN 1 END) AS severe_error,
        COUNT (CASE WHEN total_amount > 0 AND fare_amount < 0 THEN 1 END) AS invalid_state,
        COUNT (CASE WHEN total_amount < 0 AND fare_amount = 0 THEN 1 END) AS invalid_trans,
        valid_trips + zero_amount_trips + zero_fare_trips + negative_amount_trips + data_corrupt + severe_error + invalid_state + invalid_trans AS total_class
    FROM combined_trips
    """
).df()

,total_trips,valid_trips,zero_amount_trips,zero_fare_trips,negative_amount_trips,data_corrupt,severe_error,invalid_state,invalid_trans,total_class
0,48722602,45851901,6334,10306,968747,467,0,1879873,4974,48722602

In [32]:
conn.execute(
    """ 
    SUMMARIZE (
        SELECT (*) 
        FROM combined_trips
        WHERE total_amount = 0 AND fare_amount <= 0
        ORDER BY tpep_pickup_datetime ASC
    )
    """
).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,6,3,1.121408272813388,0.4660657471069113,1,1,1,6334,0.0
1,tpep_pickup_datetime,TIMESTAMP,2025-01-01 01:30:13,2025-12-31 20:58:45,8558,2025-07-02 13:31:09.49258,None,2025-04-04 20:09:55.186157,2025-06-30 18:08:09.635827,2025-09-29 03:31:02.344874,6334,0.0
2,tpep_dropoff_datetime,TIMESTAMP,2025-01-01 01:30:31,2025-12-31 20:58:45,5818,2025-07-02 13:40:39.355226,None,2025-04-04 20:19:53.835426,2025-06-30 18:17:14.230471,2025-09-29 03:42:47.273104,6334,0.0
3,passenger_count,BIGINT,0,6,7,1.0583709650443218,0.4455325496453634,1,1,1,6334,5.6
4,trip_distance,DOUBLE,0.0,19447.8,463,4.60752131354591,244.39368279963915,0.0,0.09953598484848485,1.2214477508650516,6334,0.0
5,RatecodeID,BIGINT,1,99,6,6.328650275965881,21.512976633525533,1,1,1,6334,5.6
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,6334,5.6
7,PULocationID,INTEGER,1,265,231,156.52794442690242,68.84372276535717,107,153,230,6334,0.0
8,DOLocationID,INTEGER,1,265,213,161.22166087780235,73.18277410300153,108,161,234,6334,0.0
9,payment_type,BIGINT,0,5,6,3.0050520997789705,1.148931655756106,2,3,4,6334,0.0
10,fare_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,6334,0.0
11,extra,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,6334,0.0
12,mta_tax,DOUBLE,0.0,0.5,2,0.0027628670666245657,0.03706773564849562,0.0,0.0,0.0,6334,0.0
13,tip_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,6334,0.0
14,tolls_amount,DOUBLE,0.0,6.94,2,0.0032870224186927694,0.15101235524760814,0.0,0.0,0.0,6334,0.0
15,improvement_surcharge,DOUBLE,0.0,0.3,2,0.00165772023997474,0.02224064138909737,0.0,0.0,0.0,6334,0.0
16,total_amount,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,6334,0.0
17,congestion_surcharge,DOUBLE,0.0,2.5,2,0.006690081953503931,0.12916360939889682,0.0,0.0,0.0,6334,5.6
18,Airport_fee,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,6334,5.6
19,cbd_congestion_fee,DOUBLE,0.0,0.75,2,0.017642879696874014,0.11367906058874234,0.0,0.0,0.0,6334,0.0

In [31]:
conn.execute(
    """ 
    SUMMARIZE (
        SELECT (*) 
        FROM combined_trips
        WHERE total_amount <= 0
        ORDER BY tpep_pickup_datetime ASC
    )
    """
).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,6,3,1.9961530694874772,0.11732702197943566,2,2,2,980522,0.00
1,tpep_pickup_datetime,TIMESTAMP,2025-01-01 00:00:00,2025-12-31 23:57:56,975761,2025-07-13 13:54:50.883455,None,2025-04-23 18:29:13.794692,2025-07-14 13:14:38.569641,2025-10-15 09:46:30.501965,980522,0.00
2,tpep_dropoff_datetime,TIMESTAMP,2025-01-01 00:00:00,2026-01-01 00:27:38,973500,2025-07-13 14:11:51.11551,None,2025-04-23 18:32:30.123184,2025-07-14 18:04:53.563966,2025-10-15 10:16:42.093086,980522,0.00
3,passenger_count,BIGINT,0,9,9,1.389378472384619,0.776578306909486,1,1,2,980522,17.14
4,trip_distance,DOUBLE,0.0,321242.41,4084,7.028401535101006,656.1754432248994,0.7052405955208721,1.6760534136162462,5.458656325433678,980522,0.00
5,RatecodeID,BIGINT,1,99,7,1.307930514152929,2.5725761348587786,1,1,1,980522,17.14
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,980522,17.14
7,PULocationID,INTEGER,1,265,266,155.10472483024347,62.81977095777139,127,145,226,980522,0.00
8,DOLocationID,INTEGER,1,265,290,154.33987100748377,71.57428215924061,94,160,230,980522,0.00
9,payment_type,BIGINT,0,5,6,2.8142336428963346,1.4956527359807401,2,4,4,980522,0.00
10,fare_amount,DOUBLE,-1807.6,59.76,4940,-21.04344096307884,28.304468124969187,-23.745978435156818,-11.412852642205852,-6.4970872040047505,980522,0.00
11,extra,DOUBLE,-10.0,0.0,35,-0.8855569890323725,1.4529025885733555,-1.0,0.0,0.0,980522,0.00
12,mta_tax,DOUBLE,-0.5,0.5,3,-0.3034699884347317,0.3806657399684857,-0.5,-0.5,-0.5,980522,0.00
13,tip_amount,DOUBLE,-333.33,255.3,1886,0.01827160430872539,1.159656533875478,0.0,0.0,0.0,980522,0.00
14,tolls_amount,DOUBLE,-148.17,42.0,1194,-0.5246438325708648,2.9163336356069918,0.0,0.0,0.0,980522,0.00
15,improvement_surcharge,DOUBLE,-1.0,1.0,4,-0.6498600745317284,0.7540313723765083,-1.0,-1.0,-1.0,980522,0.00
16,total_amount,DOUBLE,-1832.85,0.0,13048,-25.302336337174296,30.84590172983762,-28.78744100059425,-16.151965764266492,-9.397151413493066,980522,0.00
17,congestion_surcharge,DOUBLE,-2.5,2.5,4,-1.9566544243441701,1.0312050047505297,-2.5,-2.5,-2.5,980522,17.14
18,Airport_fee,DOUBLE,-1.75,0.0,2,-0.35923718925465425,0.7068340243477506,0.0,0.0,0.0,980522,17.14
19,cbd_congestion_fee,DOUBLE,-0.75,0.75,3,-0.31109118408358,0.5046138747007856,-0.75,-0.75,0.0,980522,0.00

In [30]:
conn.execute(
    """ 
    SUMMARIZE (
        SELECT (*) 
        FROM combined_trips
        WHERE fare_amount <= 0
        ORDER BY tpep_pickup_datetime ASC
    )
    """
).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,6,3,1.9999324096920321,0.10978467778016307,2,2,2,2870234,0.00
1,tpep_pickup_datetime,TIMESTAMP,2025-01-01 00:00:00,2025-12-31 23:57:56,2515509,2025-07-11 16:45:46.226855,None,2025-04-30 18:50:17.680497,2025-07-15 04:33:58.283571,2025-10-08 09:33:39.401851,2870234,0.00
2,tpep_dropoff_datetime,TIMESTAMP,2025-01-01 00:00:00,2026-01-01 00:27:38,3174336,2025-07-11 17:03:28.164007,None,2025-05-01 22:42:41.784507,2025-07-15 19:18:24.024454,2025-10-07 22:28:49.024666,2870234,0.00
3,passenger_count,BIGINT,0,9,9,1.3880828560556537,0.7760028872040522,1,1,2,2870234,71.43
4,trip_distance,DOUBLE,0.0,321242.41,4380,14.232981725531257,1145.151388273739,1.0526202677981802,2.2414246886949276,4.667854502695316,2870234,0.00
5,RatecodeID,BIGINT,1,99,7,1.4254349162365476,4.191314136902795,1,1,1,2870234,71.43
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,2870234,71.43
7,PULocationID,INTEGER,1,265,266,153.4966211814089,70.39048863841082,98,149,230,2870234,0.00
8,DOLocationID,INTEGER,1,265,290,152.96422103563683,72.57675545018373,89,158,230,2870234,0.00
9,payment_type,BIGINT,0,5,6,0.9671169667699567,1.5962640110527426,0,0,2,2870234,0.00
10,fare_amount,DOUBLE,-1807.6,0.0,4783,-9.808458508957225,18.489621351793023,-7.920476518576559,-4.75,-3.9995793671489124,2870234,0.00
11,extra,DOUBLE,-10.0,133.6,52,-0.30189699167384954,0.952154917741141,0.0,0.0,0.0,2870234,0.00
12,mta_tax,DOUBLE,-0.5,5.8,4,0.2244220506063269,0.4411977729326946,-0.5,0.5,0.5,2870234,0.00
13,tip_amount,DOUBLE,-333.33,255.3,1919,0.008233405359981094,0.7794336146100292,0.0,0.0,0.0,2870234,0.00
14,tolls_amount,DOUBLE,-148.17,300.0,1462,0.030431818451040572,2.1726702404346296,0.0,0.0,0.0,2870234,0.00
15,improvement_surcharge,DOUBLE,-1.0,1.0,4,0.4352106483304155,0.8978972152299084,-1.0,1.0,1.0,2870234,0.00
16,total_amount,DOUBLE,-1832.85,300.0,16035,-5.797433839888681,22.990928658290716,-9.950441961206392,2.6276419671387146,4.489479168964514,2870234,0.00
17,congestion_surcharge,DOUBLE,-2.5,2.5,4,-1.9224236762252296,1.0922055111348803,-2.5,-2.5,-2.5,2870234,71.43
18,Airport_fee,DOUBLE,-1.75,1.75,3,-0.355116851723566,0.7059391811741018,0.0,0.0,0.0,2870234,71.43
19,cbd_congestion_fee,DOUBLE,-0.75,1.5,4,0.2660529594451184,0.5731660999804563,0.0,0.75,0.75,2870234,0.00

In [25]:
conn.execute(
    """ 
    SELECT (*) 
    FROM combined_trips
    WHERE tpep_pickup_datetime <= '2025-01-01'
    ORDER BY tpep_pickup_datetime ASC
    LIMIT 10
    """
).df()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2007-12-05 18:45:00,2007-12-05 19:02:00,1,3.00,1,N,142,234,2,17.0,1.0,0.5,0.00,0.00,1.0,22.75,2.5,0.00,0.75
1,2,2008-12-31 23:04:21,2008-12-31 23:32:25,1,18.12,2,N,132,238,2,70.0,0.0,0.5,0.00,6.94,1.0,80.94,2.5,0.00,0.00
2,2,2009-01-01 00:05:50,2009-01-01 00:10:56,1,1.26,1,N,239,50,2,8.6,1.0,0.5,0.00,0.00,1.0,14.35,2.5,0.00,0.75
3,2,2009-01-01 00:19:34,2009-01-01 01:10:21,6,10.77,1,N,138,239,2,52.7,5.0,0.5,0.00,6.94,1.0,70.39,2.5,1.75,0.00
4,2,2009-01-01 00:20:39,2009-01-01 00:20:49,5,4.47,1,N,230,261,1,24.0,1.0,0.5,2.98,0.00,1.0,32.73,2.5,0.00,0.75
5,2,2009-01-01 08:52:26,2009-01-01 10:00:26,1,11.95,1,N,138,163,1,64.6,0.0,0.5,16.65,13.88,1.0,99.88,2.5,0.00,0.75
6,2,2009-01-01 12:52:15,2009-01-01 13:12:15,1,2.13,1,N,43,230,1,18.4,0.0,0.5,4.63,0.00,1.0,27.78,2.5,0.00,0.75
7,2,2009-01-01 14:08:04,2009-01-01 14:45:04,1,11.56,1,N,138,142,2,50.6,0.0,0.5,0.00,13.88,1.0,68.48,2.5,0.00,0.00
8,2,2024-12-31 20:47:55,2024-12-31 20:54:00,2,1.72,1,N,48,246,1,9.3,1.0,0.5,2.86,0.00,1.0,17.16,2.5,0.00,0.00
9,2,2024-12-31 20:52:50,2024-12-31 21:09:34,2,5.05,1,N,249,262,1,23.3,1.0,0.5,4.00,0.00,1.0,32.30,2.5,0.00,0.00

In [22]:
conn.execute(
    """ 
    SELECT (*) 
    FROM combined_trips
    WHERE tpep_pickup_datetime <= '2023-01-01 00:00'
    """
).df()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2009-01-01 00:19:34,2009-01-01 01:10:21,6,10.77,1,N,138,239,2,52.7,5.0,0.5,0.00,6.94,1.0,70.39,2.5,1.75,0.00
1,2,2007-12-05 18:45:00,2007-12-05 19:02:00,1,3.00,1,N,142,234,2,17.0,1.0,0.5,0.00,0.00,1.0,22.75,2.5,0.00,0.75
2,2,2009-01-01 00:20:39,2009-01-01 00:20:49,5,4.47,1,N,230,261,1,24.0,1.0,0.5,2.98,0.00,1.0,32.73,2.5,0.00,0.75
3,2,2009-01-01 08:52:26,2009-01-01 10:00:26,1,11.95,1,N,138,163,1,64.6,0.0,0.5,16.65,13.88,1.0,99.88,2.5,0.00,0.75
4,2,2009-01-01 12:52:15,2009-01-01 13:12:15,1,2.13,1,N,43,230,1,18.4,0.0,0.5,4.63,0.00,1.0,27.78,2.5,0.00,0.75
5,2,2008-12-31 23:04:21,2008-12-31 23:32:25,1,18.12,2,N,132,238,2,70.0,0.0,0.5,0.00,6.94,1.0,80.94,2.5,0.00,0.00
6,2,2009-01-01 00:05:50,2009-01-01 00:10:56,1,1.26,1,N,239,50,2,8.6,1.0,0.5,0.00,0.00,1.0,14.35,2.5,0.00,0.75
7,2,2009-01-01 14:08:04,2009-01-01 14:45:04,1,11.56,1,N,138,142,2,50.6,0.0,0.5,0.00,13.88,1.0,68.48,2.5,0.00,0.00

In [103]:
conn.execute(
    """     
    CREATE OR REPLACE TABLE flag_combined AS 
    WITH nunique AS (
        SELECT DISTINCT * 
        FROM combined_trips
    ), calculate AS (
        SELECT *,
        trip_distance >= 50 AS extreme_dist_flag,
        EPOCH(tpep_dropoff_datetime - tpep_pickup_datetime)/ 3600 AS duration_hours,
        EPOCH(tpep_dropoff_datetime - tpep_pickup_datetime)/ 60 AS duration_mins,
        FROM nunique
    ), 
    speed AS (
        SELECT *,
            trip_distance / duration_hours AS speed_mph,
            EXTRACT('hour' FROM tpep_pickup_datetime) AS pickup_hour,
            EXTRACT('dow' FROM tpep_pickup_datetime) AS pickup_dow,
            dayname(tpep_pickup_datetime) AS pickup_dayofw,
            CASE WHEN fare_amount > 0 THEN tip_amount / fare_amount ELSE NULL END AS tip_rate,
            CASE WHEN trip_distance > 0 THEN fare_amount / trip_distance ELSE NULL END AS fare_permile,

        FROM calculate
    )
    SELECT *,
        speed_mph > 80 OR speed_mph < 0 OR speed_mph  IS NULL AS impossible_speed,
    FROM speed;
    """
)

conn.execute(
    """ 
    SELECT 
        SUM(impossible_speed) AS count_speed,
        SUM(extreme_dist_flag) AS count_extreme_dist
    FROM flag_combined;
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   count_speed  count_extreme_dist
0     559992.0              9159.0

In [ ]:
conn.execute(
    """ 
    COPY (
        SELECT 
            tpep_pickup_datetime,
            tpep_dropoff_datetime,
            passenger_count,
            trip_distance,
            PULocationID,
            DOLocationID,
            payment_type,
            fare_amount,
            tip_amount,
            total_amount,
            duration_hours,
            duration_mins,
            speed_mph,
            pickup_hour,
            pickup_dow,
            pickup_dayofw,
            tip_rate,
            fare_permile
        FROM flag_combined
        WHERE 
            tpep_pickup_datetime < tpep_dropoff_datetime
            AND tpep_pickup_datetime > '2023-01-01 00:00'
            AND trip_distance BETWEEN 0.01 AND 100
            AND (fare_permile <= 100 AND fare_permile >= 0)
            AND fare_permile BETWEEN 0 AND 200
            AND passenger_count > 0
            AND (total_amount > 0 AND fare_amount >= 0)
            AND (speed_mph < 80 AND speed_mph > 0)
    ) TO "../data/processed/clean_taxinyc_2025.parquet"
    (FORMAT PARQUET, COMPRESSION ZSTD)
    """
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [111]:
conn.close()

In [4]:
diss = duckdb.connect('clean_taxinyc.db')

In [115]:
diss.execute (
    """ 
    CREATE OR REPLACE TABLE clean_taxinyc AS SELECT * FROM '../data/processed/clean_taxinyc_2025.parquet';
    """
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [116]:
diss.execute(
    """ 
    SUMMARIZE clean_taxinyc
    """
).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,VendorID,INTEGER,1,2,2,1.7818989276154056,0.412956413543637,2,2,2,34962923,0.00
1,tpep_pickup_datetime,TIMESTAMP,2024-12-31 20:47:55,2025-12-31 23:59:54,17356281,2025-07-02 22:40:59.729215,None,2025-04-03 04:39:39.083647,2025-06-29 06:55:46.610344,2025-10-05 04:01:14.087082,34962923,0.00
2,tpep_dropoff_datetime,TIMESTAMP,2024-12-31 20:54:00,2026-01-01 23:00:06,18977580,2025-07-02 22:58:31.286059,None,2025-04-03 03:14:32.071719,2025-06-29 01:17:40.168612,2025-10-05 01:31:29.882198,34962923,0.00
3,passenger_count,BIGINT,1,9,10,1.300851276078948,0.7200164253201979,1,1,1,34962923,0.00
4,trip_distance,DOUBLE,0.01,99.82,5634,3.4338338373481196,4.536590896522592,1.0190583655367407,1.7199288580609182,3.340898771695036,34962923,0.00
5,RatecodeID,BIGINT,1,99,7,3.276224130345166,14.517499808107079,1,1,1,34962923,0.00
6,store_and_fwd_flag,VARCHAR,N,Y,2,None,None,None,None,None,34962923,0.00
7,PULocationID,INTEGER,1,265,290,165.09588520387726,63.20666505272338,132,162,233,34962923,0.00
8,DOLocationID,INTEGER,1,265,298,164.69594893424673,69.23407593369913,115,162,234,34962923,0.00
9,payment_type,BIGINT,1,5,5,1.1738319762337948,0.49042704042688884,1,1,1,34962923,0.00
10,fare_amount,DOUBLE,0.0,963.0,7608,19.636723202463454,18.17362016630726,9.299853644887854,13.476823775522456,21.946711831158964,34962923,0.00
11,extra,DOUBLE,-17.39,16.19,111,1.5975902506778399,1.9168810023950675,0.0,1.0,2.5,34962923,0.00
12,mta_tax,DOUBLE,0.0,5243.38,16,0.4947120287969058,0.8883688770698265,0.5,0.5,0.5,34962923,0.00
13,tip_amount,DOUBLE,0.0,960.94,6145,3.7045712828413024,4.072781264225063,1.1767215856368471,2.990951459743526,4.5889832241526385,34962923,0.00
14,tolls_amount,DOUBLE,0.0,916.87,2902,0.5871530583962683,2.231569766528643,0.0,0.0,0.0,34962923,0.00
15,improvement_surcharge,DOUBLE,0.0,1.0,2,0.9778102076877268,0.14730039392342112,1.0,1.0,1.0,34962923,0.00
16,total_amount,DOUBLE,0.5,5297.87,30141,29.400872680767293,22.86543288640185,16.58994718624487,21.740293588277503,31.3697477317172,34962923,0.00
17,congestion_surcharge,DOUBLE,0.0,2.5,4,2.287789224602302,0.6967731562657502,2.5,2.5,2.5,34962923,0.00
18,Airport_fee,DOUBLE,0.0,5.0,5,0.15430354607365065,0.4962076035914359,0.0,0.0,0.0,34962923,0.00
19,cbd_congestion_fee,DOUBLE,-0.75,1.25,4,0.5538857692190096,0.32958297093570643,0.0,0.75,0.75,34962923,0.00
20,extreme_dist_flag,BOOLEAN,false,true,2,None,None,None,None,None,34962923,0.00
21,duration_hours,DOUBLE,0.0005555555555555556,146.65333333333334,20436,0.29209912313553993,0.49017838661919266,0.12959790351678283,0.21303909553523515,0.3502976355348968,34962923,0.00
22,duration_mins,DOUBLE,0.03333333333333333,8799.2,15255,17.525947388132803,29.41070319715143,7.763851470924081,12.777480145015637,21.029495478141442,34962923,0.00
23,speed_mph,DOUBLE,0.0009547298910016707,79.99999999999999,2721866,10.752559048761093,6.299950098752805,6.799147280963789,9.160413954947671,12.61669324071029,34962923,0.00
24,pickup_hour,BIGINT,0,23,24,14.423795201562523,5.640780832507568,11,15,19,34962923,0.00
25,pickup_dow,BIGINT,0,6,7,3.1213715169066383,1.9452713122549046,1,3,5,34962923,0.00
26,pickup_dayofw,VARCHAR,Friday,Wednesday,7,None,None,None,None,None,34962923,0.00
27,tip_rate,DOUBLE,0.0,20000.0,162873,0.2188529735993548,4.830532630472652,0.10606417192859484,0.2501144799702696,0.3045467473788323,34962923,0.01
28,fare_permile,DOUBLE,0.0,100.0,279214,8.231673758988478,4.590613845870727,5.785017197392164,7.406991176022557,9.478430991443814,34962923,0.00
29,impossible_speed,BOOLEAN,false,false,1,None,None,None,None,None,34962923,0.00

In [97]:
diss.execute("""
    SELECT 
        MAX(fare_amount) AS max_fare,
        MAX(tip_amount) AS max_tip,
        MAX(tolls_amount) AS max_tolls,
        MAX(total_amount) AS max_total,
        MAX(duration_hours) AS max_duration,
        MAX(speed_mph) AS max_speed,
        MAX(fare_permile) AS max_fare_permile
    FROM clean_taxinyc;
""").df()

,max_fare,max_tip,max_tolls,max_total,max_duration,max_speed,max_fare_permile
0,963.0,960.94,916.87,5297.87,146.653333,80.0,100.0

In [84]:
diss.execute("""
    SELECT * 
    FROM clean_taxinyc 
    WHERE fare_amount > 1000 OR trip_distance > 1000;
""").df()

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, cbd_congestion_fee, extreme_dist_flag, duration_hours, duration_mins, speed_mph, pickup_hour, pickup_dow, pickup_dayofw, tip_rate, fare_permile, impossible_speed]
Index: []

[0 rows x 30 columns]

In [127]:
#Hourly mart demand
diss.execute (
    """ 
    COPY (SELECT
        pickup_hour,
        SUM(passenger_count) AS total_passengers,
        COUNT(*) AS trip_count,
        AVG(trip_distance) AS avg_trip_distance,
        SUM(total_amount) AS revenue,
        AVG(tip_rate) * 100 AS avg_tip_rate,
        AVG(duration_mins) AS avg_duration,
    FROM clean_taxinyc
    GROUP BY pickup_hour
    ORDER BY pickup_hour ASC)
    
    TO "../data/marts/mart_duck_hourly.parquet"
    (FORMAT PARQUET, COMPRESSION ZSTD)
    """
)

In [131]:
#Daily mart demand
diss.execute (
    """ 
    COPY (
        SELECT
            pickup_dayofw,
            pickup_dow,
            SUM(passenger_count) AS total_passengers,
            COUNT(*) AS trip_count,
            AVG(trip_distance) AS avg_trip_distance,
            SUM(total_amount) AS revenue,
            AVG(tip_rate) * 100 AS avg_tip_rate,
            AVG(duration_mins) AS avg_duration,
        FROM clean_taxinyc
        GROUP BY pickup_dayofw, pickup_dow
        ORDER BY pickup_dow ASC
    ) TO "../data/marts/mart_duck_daily.parquet"
    """
)

In [135]:
#Pickup zone demand
diss.execute (
    """ 
    COPY (
        SELECT
                PULocationID,
                SUM(passenger_count) AS total_passengers,
                COUNT(*) AS trip_count,
                AVG(trip_distance) AS avg_trip_distance,
                SUM(total_amount) AS revenue,
                AVG(tip_rate) * 100 AS avg_tip_rate,
                AVG(duration_mins) AS avg_duration,
            FROM clean_taxinyc
            GROUP BY PULocationID
            ORDER BY trip_count DESC
            LIMIT 20
    ) TO "../data/marts/mart_duck_pickup.parquet"
    """
)

In [136]:
#Common Dropoff
diss.execute (
    """ 
    COPY (
        SELECT
            DOLocationID,
            SUM(passenger_count) AS total_passengers,
            COUNT(*) AS trip_count,
            AVG(trip_distance) AS avg_trip_distance,
            SUM(total_amount) AS revenue,
            AVG(tip_rate) * 100 AS avg_tip_rate,
            AVG(duration_mins) AS avg_duration,
        FROM clean_taxinyc
        GROUP BY DOLocationID
        ORDER BY trip_count DESC
    LIMIT 20
    ) TO "../data/marts/mart_duck_dropoff.parquet"
    """
)

In [137]:
#Distance distribution
diss.execute (
    """ 
    COPY (
        WITH binned_data AS (
        SELECT
            passenger_count,
            trip_distance,
            total_amount,
            tip_rate,
            duration_mins,
            
            CASE 
                WHEN trip_distance >= 0 AND trip_distance < 1 THEN '0-1 mile'
                WHEN trip_distance >= 1 AND trip_distance < 3 THEN '1-3 miles'
                WHEN trip_distance >= 3 AND trip_distance < 7 THEN '3-7 miles'
                WHEN trip_distance >= 7 AND trip_distance < 15 THEN '5-10 miles'
                WHEN trip_distance >= 15 THEN '15+ miles'
            END AS distance_group
        FROM clean_taxinyc)
        
        SELECT
            distance_group,
            SUM(passenger_count) AS total_passengers,
            COUNT(*) AS trip_count,
            AVG(trip_distance) AS avg_trip_distance,
            SUM(total_amount) AS revenue,
            AVG(tip_rate) * 100 AS avg_tip_rate,
            AVG(duration_mins) AS avg_duration
        FROM binned_data
        GROUP BY distance_group
        ORDER BY trip_count DESC
    ) TO "../data/marts/mart_duck_dist.parquet"
    """
)

In [ ]:
#Basic
diss.execute (
    """ 
    COPY (
        
    ) TO "../data/marts/mart_duck_daily.parquet"
    """
)

In [5]:
diss.close()